from collections.abc import Sequence
from datetime import datetime
from typing import Protocol
from uuid import UUID

from event_scheduling.calendar.dto import ExternalCalendarDTO
from event_scheduling.interfaces.busy_times import BusyInterval, TimeWindow


class IICalClient(Protocol):
    async def fetch(self, url: str) -> bytes: ...


class IICalParser(Protocol):
    def expand(self, ics_bytes: bytes, window: TimeWindow) -> list[BusyInterval]: ...


class ICalendarReadAdapter(Protocol):
    async def list_enabled(self) -> list[ExternalCalendarDTO]: ...
    async def list_by_host(self, host_user_id: UUID) -> list[ExternalCalendarDTO]: ...
    async def get(self, calendar_id: UUID) -> ExternalCalendarDTO | None: ...


class ICalendarWriteAdapter(Protocol):
    async def create(self, host_user_id: UUID, url: str) -> ExternalCalendarDTO: ...
    async def delete(self, calendar_id: UUID) -> None: ...
    async def replace_cache(self, calendar_id: UUID, events: Sequence[BusyInterval]) -> None: ...
    async def mark_synced(self, calendar_id: UUID, now: datetime) -> None: ...
    async def mark_error(self, calendar_id: UUID, now: datetime, err: str) -> None: ...
