"""GetStream chat protocols."""

from typing import Protocol


class IChatClient(Protocol):
    async def create_chat(self, *, channel_id: str, organizer_id: str, client_id: str) -> None: ...
    async def has_messages(self, *, channel_id: str) -> bool: ...
    async def delete_chat(self, *, channel_id: str, hard: bool = False) -> None: ...
    async def send_message(self, *, channel_id: str, user_id: str, message: dict) -> None: ...
    async def create_token(self, *, user_id: str, name: str, expires_at: int) -> str: ...


class IChatController(Protocol):
    async def create_chat(
        self, channel_id: str, organizer_id: str, client_id: str, *, dedupe_key: str | None = None
    ) -> None: ...
    async def has_messages(self, channel_id: str) -> bool: ...
    async def delete_chat(
        self, channel_id: str, booking_uid: str, *, hard: bool = False, dedupe_key: str | None = None
    ) -> None: ...
    async def send_message(self, channel_id: str, user_id: str, message: dict) -> None: ...
