"""Booking database adapter protocol."""

from datetime import datetime
from typing import Protocol

from event_booking.dtos import AttendeeBookingDTO, BookingDTO


class IBookingDatabaseAdapter(Protocol):
    async def get_booking(self, booking_uid: str) -> BookingDTO | None: ...
    async def get_bookings(self, start_time_from: datetime, start_time_to: datetime) -> list[BookingDTO]: ...
    async def get_attendee_bookings_by_email(
        self, *, email: str, exclude_booking_id: int
    ) -> list[AttendeeBookingDTO]: ...
    async def update_booking_video_url(self, booking_uid: str, url: str) -> None: ...
    async def mark_reminder_sent(self, booking_uid: str, sent_at: datetime) -> None: ...
    async def reject_booking(self, *, booking_id: int, reason: str) -> None: ...
