"""Booking database adapter protocol."""

from datetime import datetime
from typing import Protocol

from event_booking.dtos import AttendeeBookingDTO, BookingDTO, UserDTO


class IBookingDatabaseAdapter(Protocol):
    async def get_booking(self, booking_uid: str) -> BookingDTO | None: ...
    async def get_bookings(self, start_time_from: datetime, start_time_to: datetime) -> list[BookingDTO]: ...
    async def get_attendee_bookings_by_email(self, *, email: str) -> list[AttendeeBookingDTO]: ...
    async def get_user_by_email(self, email: str) -> UserDTO | None: ...
    async def get_organizer_chat_id(self, email: str) -> int | None: ...
    async def update_booking_video_url(self, booking_uid: str, url: str) -> None: ...
    async def delete_booking_and_attendee_by_booking_id(self, *, booking_id: int) -> None: ...
