"""URL shortener protocol."""

from typing import Protocol


class IUrlShortener(Protocol):
    async def create_url(self, long_url: str, expires_at: float, not_before: float, external_id: str) -> str | None: ...
    async def get_url(self, external_id: str) -> str | None: ...
    async def update_url_data(
        self, *, long_url: str, expires_at: float, not_before: float, new_external_id: str, old_external_id: str
    ) -> str | None: ...
    async def delete_url(self, *, external_id: str) -> str | None: ...
