"""SQL executor protocol."""

from typing import Protocol

from sqlalchemy.engine import RowMapping


class ISqlExecutor(Protocol):
    async def fetch_one(self, query: str, values: dict) -> RowMapping | None: ...
    async def fetch_all(self, query: str, values: dict) -> list[RowMapping]: ...
    async def execute(self, query: str, values: dict) -> None: ...
    async def execute_in_transaction(self, statements: list[tuple[str, dict]]) -> None: ...
