-- Minimal cal.com schema fixture for the dev/integration stack.
--
-- Derived from the exact SQL event-booking runs against cal.com
-- (event-booking/event_booking/adapters/db.py): only the tables/columns it
-- reads or writes exist here. cal.com uses quoted camelCase identifiers and
-- timestamp(3) WITHOUT time zone (naive UTC) — both are preserved.
--
-- Writes performed by event-booking (kept working here):
--   * Booking.metadata ||= {'videoCallUrl': ...} and {'bookingReminderSentAt': ...}
--   * Booking.status = 'rejected' + Booking."rejectionReason" (constraints)
--
-- A real external cal.com instance can be used instead by setting
-- CALCOM_DATABASE_URL in .env (this container is then simply unused).

CREATE TABLE users (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    text,
    name        text,
    email       text NOT NULL,
    "timeZone"  text NOT NULL DEFAULT 'Europe/London',
    locale      text,
    locked      boolean NOT NULL DEFAULT false,
    telegram_chat_id bigint
);

CREATE TABLE "EventType" (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     text NOT NULL,
    slug      text NOT NULL,
    length    integer NOT NULL,
    "userId"  integer REFERENCES users (id)
);

CREATE TABLE "Booking" (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                text NOT NULL UNIQUE,
    "userId"           integer REFERENCES users (id),
    "eventTypeId"      integer REFERENCES "EventType" (id),
    title              text NOT NULL DEFAULT '',
    status             text NOT NULL DEFAULT 'accepted',
    "startTime"        timestamp(3) NOT NULL,
    "endTime"          timestamp(3) NOT NULL,
    "createdAt"        timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata           jsonb,
    "fromReschedule"   text,
    "rejectionReason"  text
);

CREATE INDEX "Booking_startTime_idx" ON "Booking" ("startTime");

CREATE TABLE "Attendee" (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bookingId"  integer NOT NULL REFERENCES "Booking" (id) ON DELETE CASCADE,
    name         text NOT NULL,
    email        text NOT NULL,
    "timeZone"   text NOT NULL,
    locale       text
);

CREATE INDEX "Attendee_bookingId_idx" ON "Attendee" ("bookingId");

-- ---------------------------------------------------------------------------
-- Seed data: matches the recorded BOOKING_CREATED webhook in
-- event-booking/requests.jsonl (uid n3FHda8Cpy48QW4JZX9th7, bookingId 347),
-- so that webhook can be replayed against the stack end-to-end.
-- ---------------------------------------------------------------------------

INSERT INTO users (id, username, name, email, "timeZone", locale, locked, telegram_chat_id)
VALUES (4, 'chief.bread', 'Александр', 'lelikovas@gmail.com', 'Europe/Madrid', 'ru', false, 154243643);

INSERT INTO "EventType" (id, title, slug, length, "userId")
VALUES (2, 'qqqqqq', 'qqqqqq', 5, 4);

INSERT INTO "Booking" (id, uid, "userId", "eventTypeId", title, status, "startTime", "endTime", "createdAt", metadata)
VALUES (
    347,
    'n3FHda8Cpy48QW4JZX9th7',
    4,
    2,
    'qqqqqq Александр',
    'accepted',
    '2026-05-12 22:05:00',
    '2026-05-12 22:10:00',
    '2026-05-12 22:01:35',
    '{}'::jsonb
);

INSERT INTO "Attendee" ("bookingId", name, email, "timeZone", locale)
VALUES (347, 'Александр', 'chied.bread@gmail.com', 'Europe/Madrid', 'ru');

-- Keep identity sequences ahead of the seeded ids.
SELECT setval(pg_get_serial_sequence('users', 'id'), 100, true);
SELECT setval(pg_get_serial_sequence('"EventType"', 'id'), 100, true);
SELECT setval(pg_get_serial_sequence('"Booking"', 'id'), 1000, true);
