from typing import Protocol
from uuid import UUID


class ISchedulingClient(Protocol):
    async def get_schedule(self, owner_user_id: UUID) -> dict: ...
    async def put_schedule(self, owner_user_id: UUID, body: dict) -> dict: ...
    async def put_travel(self, owner_user_id: UUID, body: dict) -> dict: ...
    async def get_bookings(self, host_user_id: UUID) -> list[dict]: ...


class IUsersClient(Protocol):
    async def get_user(self, user_id: UUID) -> dict: ...
    async def patch_user(self, user_id: UUID, body: dict) -> dict: ...
    async def resolve_organizer(self, email: str) -> UUID | None: ...
