from typing import Protocol
from uuid import UUID


class ISchedulingClient(Protocol):
    async def get_schedule(self, owner_user_id: UUID) -> dict: ...
    async def put_schedule(self, owner_user_id: UUID, body: dict) -> dict: ...
    async def put_travel(self, owner_user_id: UUID, body: dict) -> dict: ...
    async def get_bookings(self, host_user_id: UUID) -> list[dict]: ...
    async def get_booking_detail(self, booking_id: str) -> dict: ...
    async def get_slots(self, event_type_id: str, start_iso: str, end_iso: str, time_zone: str) -> dict: ...
    async def reschedule_booking(self, booking_id: str, start_time_iso: str, actor_user_id: UUID) -> dict: ...


class IUsersClient(Protocol):
    async def get_user(self, user_id: UUID) -> dict: ...
    async def patch_user(self, user_id: UUID, body: dict) -> dict: ...
    async def resolve_organizer(self, email: str) -> UUID | None: ...
