from typing import Protocol
from uuid import UUID

from event_scheduling.dto.event_type import EventTypeDTO, UpsertEventTypeDTO


class IEventTypeDBAdapter(Protocol):
    async def insert(self, dto: UpsertEventTypeDTO) -> EventTypeDTO: ...

    async def get(self, event_type_id: UUID) -> EventTypeDTO | None: ...

    async def list_all(self) -> list[EventTypeDTO]: ...

    async def update(self, event_type_id: UUID, dto: UpsertEventTypeDTO) -> EventTypeDTO | None: ...

    async def delete(self, event_type_id: UUID) -> bool: ...


class IEventTypeController(Protocol):
    async def create(self, dto: UpsertEventTypeDTO) -> EventTypeDTO: ...

    async def get(self, event_type_id: UUID) -> EventTypeDTO: ...

    async def list_all(self) -> list[EventTypeDTO]: ...

    async def update(self, event_type_id: UUID, dto: UpsertEventTypeDTO) -> EventTypeDTO: ...

    async def delete(self, event_type_id: UUID) -> None: ...
